### ISSUE TITLE
Not all icons are rendered

### ISSUE THREAD

**Issue by woylie** [phenixdigital/phx_live_storybook#111]
I just followed the setup instructions of version 0.4.0. Some of the icons in the UI are not rendered correctly. Is there something I need to set up to make it work?

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/13847569/193183872-c862c8fb-647d-434a-be29-6e8c03f331aa.png">

Interestingly, only the icon of the active item in this element is rendered.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/13847569/193184398-00f638a6-9df9-4425-b75c-7c3c3018c73d.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/13847569/193184425-cd3637a1-b208-42a2-a0a3-a1a582eef131.png">
<img width="337" alt="image" src="https://user-images.githubusercontent.com/13847569/193184443-63622902-710e-44cc-b6b3-c5bc84bda824.png">

**Comment by matthieuchabert** [comment]
When an icon has the class `lsb` the icon does not render correctly. When I remove the `lsb` class it renders fine.

Not sure if removing the class altogether is the right solution here, waiting for @cblavier's input here.

**Comment by benregn** [comment]
It's also the icons in the sidebar that aren't rendering correctly for me.

<img width="234" alt="Screen Shot 2022-09-30 at 11 11 42 AM" src="https://user-images.githubusercontent.com/206066/193237883-ff754313-42fa-42b8-bae9-4e568e0aec8e.png">

```html
<div class="lsb lsb-flex lsb-items-center lsb-py-3 lg:lsb-py-1.5 -lsb-ml-2 lsb-group lsb-cursor-pointer lsb-group hover:lsb-text-indigo-600" phx-click="close-folder" phx-target="1" phx-value-path="/admin/storybook/components/feedback">
  <i class="fa-solid fa-caret-down lsb lsb-pl-1 lsb-pr-2"></i>
</div>
```

From my investigation, it's because the `lsb` class defines a `font-family` property which cascades down to the icon element and overrides the `font-family` of the `fa-*` classes. When I added `!important` to the `fa-*` `font-family` property, the icons render properly.

**Comment by cblavier** [comment]
Hi all, thanks for your feedback !
There is indeed an issue, I made a design choice that turns out to be a wrong one 😅 

Since you can customize all icons (including the theme picker referenced in #112) provided to the storybook with custom CSS classes (with the tuple `{:fa, icon, style, css}` I wanted the CSS bit to be interpreted within your sandbox. But it obviously raises more issues than it solves.

To fix this I think I will:
- remove CSS `sandbox` around user provided icons (sidebar, tabs & theme picker)
- correct the `icons.md` guide to let people know they must style their icons with storybook CSS classes (prefixed with  `lsb-`)
- make sure the css bundled with storybook packages enough Tailwind styles to fit most icon styling use cases (`w-*` `h-*` `p-*` `m-*` and `text-colors`)

Until then, you can avoid overriding FontAwesome font-family with:

```css
/* instead of * { ... } */
:not(i) { 
  font-family: ...
}
```


WDYT?

**Comment by woylie** [comment]
Sounds good to me!
