### ISSUE TITLE
How to support >1 function in a :component

### ISSUE THREAD

**Issue by glennr** [phenixdigital/phx_live_storybook#43]
I'd like to mix different components together in the same Entry. Something like this:

```
defmodule BrmblWeb.Storybook.Components.Typography do
  use PhxLiveStorybook.Entry, :component

  alias BrmblWeb.UI.Typography

  def description, do: "Typography components"

  def stories do
    [
      %Story{
        id: :h1,
        function: &Typography.h1/1,
        attributes: %{},
        slots: [~s|.h1 heading|]
      },
      %Story{
        id: :h2,
        function: &Typography.h2/1,
        attributes: %{},
        slots: [~s|.h2 heading|]
      }
    ]
  end
end
```

That doesn't work since a `:component` assumes all the same `:function`:

```
app1_1  | == Compilation error in file lib/brmbl_web/storybook.ex ==
app1_1  | ** (KeyError) key :function not found
app1_1  |     (phx_live_storybook 0.3.0) expanding struct: PhxLiveStorybook.Story.__struct__/1
app1_1  |     storybook/components/typography.exs:16: BrmblWeb.Storybook.Components.Typography.stories/0
```

Is this a good idea? If so, do you have any plans to add this already (or can you share any tips on how you might like to see it implemented?)

**Comment by cblavier** [comment]
I had been thinking about it today. At first, it seemed like a good idea to me, and I really get what you're trying to do on the stories tab.

But then, I tried to figure out how this would work with the playground, and it doesn't look like a good idea anymore :)
You need to declare attribute definition at the module level but you cannot have any guarantee that all the functions you are using share the same API, so that would be clumsy at best.

If I take your Typography example, I guess I would rather use a wrapper component with a single function for all headings:
```elixir
<.heading level={1}>My title</.heading>
<.heading level={2}>My title</.heading>
```
